version: '3.7'
services:
  app:
    build:
      context: .
    volumes:
      - type: bind
        source: './workspace'
        target: '/workspace'
  app2:
    build:
      context: .
      dockerfile: './app2.Dockerfile'
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - type: bind
        source: './workspace'
        target: '/workspace'

